version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "monster_strike_frontend"
    env_file:
      - ./frontend/.env
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app-frontend
    depends_on:
      - backend
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "monster_strike_backend"
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    working_dir: /app-backend
    depends_on:
      - mongo_seed
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: "monster_strike_database"
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - default

  mongo_seed:
    env_file:
      - .env
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongodb
    networks:
      - default

networks:
  default:
    name: monster_strike_net
